export const MUTATE_ADD_TODO = "ADD_TODO";
export const MUTATE_DELETE_TODO = "DELETE_TODO";
export const MUTATE_UPDATE_TODO = "UPDATE_TODO";
export const MUTATE_TOGGLE_CHECK_ALL_TODO = "TOGGLE_CHECK_ALL_TODO";
export const MUTATE_SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const MUTATE_SET_EDITED_TODO_ID = "SET_EDITED_TODO_ID";

export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO_TEXT = "EDIT_TODO_TEXT";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const TOGGLE_CHECKED_ALL_TODO = "TOGGLE_CHECKED_ALL_TODO";
export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const SET_EDITED_TODO_ID = "SET_EDITED_TODO_ID";
